library(GenomicRanges)
args <- commandArgs(TRUE)
dat <- read.csv(file=args[1],sep='\t',header=F)
colnames(dat) <- c('chr','start','end','size','score')
dat$strand <- rep("+",nrow(dat))
head(dat)
gr <- makeGRangesFromDataFrame(dat)
head(gr)
gr_disjoin <- disjoin(gr)
dat_disjoin <- data.frame(seqnames(gr_disjoin),start(gr_disjoin),end(gr_disjoin))
write.table(dat_disjoin,quote=F,row.names=F,col.names=F,file=args[2],sep='\t')
