library(GenomicRanges)
args <- commandArgs(TRUE)
dat <- read.csv(file=args[1],sep='\t',header=F)
colnames(dat) <- c('chr','start','end')
dat$strand <- rep("+",nrow(dat))
head(dat)
gr <- makeGRangesFromDataFrame(dat)
head(gr)
gr_reduce <- reduce(gr)
dat_reduce <- data.frame(seqnames(gr_reduce),start(gr_reduce),end(gr_reduce))
write.table(dat_reduce,quote=F,row.names=F,col.names=F,file=args[2],sep='\t')
